/* Luxro.Fashion storefront. Update STORE_NAME and WHATSAPP_NUMBER before publishing. */
const STORE_NAME = 'Arbimo';
const WHATSAPP_NUMBER = '919029800745'; // Replace with your WhatsApp number country code included; digits only.
const moneyLabel = 'Price on request';
let products = [], activeCategory = 'All', searchTerm = '', sortMode = 'featured', visibleCount = 12;
let bag = JSON.parse(localStorage.getItem('littleNestBag') || '{}');
const $ = s => document.querySelector(s);
const grid = $('#productGrid');
const safe = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const imageUrl = name => 'assets/products/' + encodeURIComponent(name).replace(/%2F/g,'/');
function categories(){const counts={};products.forEach(p=>counts[p.category]=(counts[p.category]||0)+1);const box=$('#filters');box.innerHTML=`<button class="filter active" data-category="All">Everything <span class="filter-count">${products.length}</span></button>`+Object.entries(counts).sort((a,b)=>a[0].localeCompare(b[0])).map(([c,n])=>`<button class="filter" data-category="${safe(c)}">${safe(c)} <span class="filter-count">${n}</span></button>`).join('');box.addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(!b)return;activeCategory=b.dataset.category;visibleCount=12;box.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));renderProducts();});}
function filtered(){let arr=products.filter(p=>(activeCategory==='All'||p.category===activeCategory)&&(`${p.name} ${p.category} ${p.id} ${p.sku}`.toLowerCase().includes(searchTerm)));if(sortMode==='az')arr.sort((a,b)=>a.name.localeCompare(b.name));if(sortMode==='za')arr.sort((a,b)=>b.name.localeCompare(a.name));return arr;}
function renderProducts(){const arr=filtered();$('#resultCount').textContent=`${arr.length} little ${arr.length===1?'find':'finds'}`;const shown=arr.slice(0,visibleCount);grid.innerHTML=shown.length?shown.map((p,i)=>`<article class="product-card" data-id="${p.id}"><div class="product-photo"><img loading="lazy" src="${imageUrl(p.image)}" alt="${safe(p.name)}" onerror="this.style.opacity='.15'"><span class="product-id">${p.id}</span><button class="quick-add" data-add="${p.id}" aria-label="Add ${safe(p.name)} to bag">+</button></div><div class="product-info"><div class="product-category">${safe(p.category)}</div><h3 class="product-name">${safe(p.name)}</h3><div class="product-meta"><span>${safe(p.size||'Everyday essential')}</span><span>${safe(p.sku)}</span></div><div class="product-price">${moneyLabel} <span>↗</span></div></div></article>`).join(''):`<div class="empty-results"><h3>No little finds just yet.</h3><p>Try another search or category.</p></div>`;$('#loadMore').hidden=arr.length<=visibleCount;if(window.anime&&shown.length){anime({targets:'.product-card',opacity:[0,1],translateY:[14,0],delay:anime.stagger(35),duration:500,easing:'easeOutCubic'});}}
function persist(){localStorage.setItem('littleNestBag',JSON.stringify(bag));renderBag();}
function add(id){bag[id]=(bag[id]||0)+1;persist();$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1700);}
function count(){return Object.values(bag).reduce((a,b)=>a+b,0)}
function renderBag(){const n=count();$('#bagCount').textContent=n;$('#drawerCount').textContent=n;const entries=Object.entries(bag).filter(([,q])=>q>0);if(!entries.length){$('#cartItems').innerHTML=`<div class="empty-bag"><span>♡</span><h3>Your bag is waiting.</h3><p>Add a few little favourites to get started.</p><button class="btn btn-dark" id="continueShopping">Explore the collection →</button></div>`;return;}$('#cartItems').innerHTML=entries.map(([id,q])=>{const p=products.find(x=>x.id===id);if(!p)return '';return `<div class="cart-row"><img src="${imageUrl(p.image)}" alt="${safe(p.name)}"><div><h4>${safe(p.name)}</h4><small>${p.id} · ${moneyLabel}</small><div class="qty-controls"><button data-qty="${id}" data-delta="-1" aria-label="Decrease quantity">−</button><span>${q}</span><button data-qty="${id}" data-delta="1" aria-label="Increase quantity">+</button></div></div><button class="remove-item" data-remove="${id}" aria-label="Remove item">×</button></div>`}).join('');}
function openBag(){ $('#overlay').classList.add('open');$('#cartDrawer').classList.add('open');$('#cartDrawer').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';}
function closeBag(){ $('#overlay').classList.remove('open');$('#cartDrawer').classList.remove('open');$('#cartDrawer').setAttribute('aria-hidden','true');document.body.style.overflow='';}
function checkout(){const entries=Object.entries(bag).filter(([,q])=>q>0);if(!entries.length){openBag();return;}const lines=entries.map(([id,q])=>{const p=products.find(x=>x.id===id);return `• ${p.name} (${p.id}) × ${q}`});const msg=`Hello ${STORE_NAME}! I'd like to enquire about these products:\n\n${lines.join('\n')}\n\nPlease confirm availability, final prices and delivery details.`;if(!/^\d{10,15}$/.test(WHATSAPP_NUMBER)){alert('Add your WhatsApp number in app.js (WHATSAPP_NUMBER) to enable direct checkout. Your selected products are saved in the bag.');return;}window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(msg)}`,'_blank','noopener');}
document.addEventListener('click',e=>{const a=e.target.closest('[data-add]');if(a){add(a.dataset.add);return;}const q=e.target.closest('[data-qty]');if(q){const id=q.dataset.qty;bag[id]=Math.max(0,(bag[id]||0)+Number(q.dataset.delta));if(!bag[id])delete bag[id];persist();return;}const r=e.target.closest('[data-remove]');if(r){delete bag[r.dataset.remove];persist();return;}if(e.target.id==='continueShopping'){closeBag();$('#shop').scrollIntoView({behavior:'smooth'});}});
$('#search').addEventListener('input',e=>{searchTerm=e.target.value.trim().toLowerCase();visibleCount=12;renderProducts()});$('#sort').addEventListener('change',e=>{sortMode=e.target.value;renderProducts()});$('#loadMore').addEventListener('click',()=>{visibleCount+=12;renderProducts()});$('#bagOpen').addEventListener('click',openBag);$('#bagClose').addEventListener('click',closeBag);$('#overlay').addEventListener('click',closeBag);$('#checkout').addEventListener('click',checkout);$('#menuToggle').addEventListener('click',()=>$('#nav').classList.toggle('open'));$('#nav').addEventListener('click',e=>{if(e.target.closest('a'))$('#nav').classList.remove('open')});$('#year').textContent=new Date().getFullYear();
fetch('products.json').then(r=>{if(!r.ok)throw Error('Could not load products.json');return r.json()}).then(data=>{products=data;categories();renderProducts();renderBag();if(window.anime){anime({targets:'.hero-copy > *',opacity:[0,1],translateY:[18,0],delay:anime.stagger(100),duration:750,easing:'easeOutCubic'});anime({targets:'.hero-image-wrap',opacity:[0,1],scale:[.94,1],duration:1100,easing:'easeOutExpo',delay:180});anime({targets:'.floating-tag',translateY:[8,-5],direction:'alternate',loop:true,duration:2600,easing:'easeInOutSine',delay:anime.stagger(300)});const obs=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){anime({targets:entry.target,opacity:[0,1],translateY:[22,0],duration:700,easing:'easeOutCubic'});obs.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.story-copy,.story-visual,.values-head,.value-grid article,.closing').forEach(el=>{el.style.opacity=0;obs.observe(el)});}}).catch(err=>{grid.innerHTML='<div class="empty-results">Could not load the product catalogue. Please run this site through a local web server (see README).</div>';console.error(err)});
